name: space_battle_withFuelAndRotation

on:
  push:
    branches: ["8thTask"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./SpaceBattle_WithRotationAndFuelProj/SpaceBattleLib

      - name: Build
        run: dotnet build ./SpaceBattle_WithRotationAndFuelProj/SpaceBattleLib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Unit-test and coverage
        run: dotnet test ./SpaceBattle_WithRotationAndFuelProj /p:CollectCoverage=true /p:ThresholdType=line /p:Threshold=100